### PR TITLE
Fix #95 - Fix Python optional generic record fields

### LINKED ISSUE #95: Invalid Python generated for records containing optional generic fields
Using yardl 2d61ba3df57d55d91c4b3e499121b9dc8f923700 with the following minimal model:

```yaml
MyRecord: !record
  fields:
    myField: RecordWithGenericOptional<string>

RecordWithGenericOptional<T>: !record
  fields:
    value: T?
```

The generated `types.py` does not properly initialize the inner record class. See generated classes below:

```python
class RecordWithGenericOptional(typing.Generic[T]):
    value: typing.Optional[T]

    def __init__(self, *,
        value: typing.Optional[T],
    ):
        self.value = value

    ...


class MyRecord:
    my_field: RecordWithGenericOptional[str]

    def __init__(self, *,
        my_field: typing.Optional[RecordWithGenericOptional[str]] = None,
    ):
        self.my_field = my_field if my_field is not None else RecordWithGenericOptional()

    ...
```

Python throws a TypeError when creating an instance of `MyRecord`:
```python
In [1]: import combined

In [2]: combined.MyRecord()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 combined.MyRecord()

File /workspaces/yardl/joe/issue-switch-over-union/python/combined/types.py:45, in MyRecord.__init__(self, my_field)
     42 def __init__(self, *,
     43     my_field: typing.Optional[RecordWithGenericOptional[str]] = None,
     44 ):
---> 45     self.my_field = my_field if my_field is not None else RecordWithGenericOptional()

TypeError: RecordWithGenericOptional.__init__() missing 1 required keyword-only argument: 'value'
```

---
In `RecordWithGenericOptional.__init__`, `value` should be instantiated with a default value of `None` because it is Optional.

However, yardl currently omits default values for *all* generic types:
https://github.com/microsoft/yardl/blob/2d61ba3df57d55d91c4b3e499121b9dc8f923700/tooling/internal/python/types/types.go#L181-L187

### PR DESCRIPTION
**Pull request by naegelejd**
Nested record fields are now correctly instantiated with proper default values in generated Python code.

### CODE REVIEW

**Comment by johnstairs** [comment]
There is another issue. 
``` yaml
MyRec<T>: !record
  fields:
    a: T*
```

Does not default the field, whereas this does: 
``` yaml
MyRec: !record
  fields:
    a: int*
```

(An existing issue, not a regression)

File: tooling/internal/python/types/types.go [hunk 1]
```diff
@@ -912,21 +913,14 @@ func typeDefinitionDefault(t dsl.TypeDefinition, contextNamespace string, st dsl
...
 		args := make([]string, 0)
-
-		for i, f := range t.Fields {
+		for _, f := range t.Fields {
 			fieldDefaultExpr, fieldDefaultKind := typeDefault(f.Type, contextNamespace, "", st)
 			if fieldDefaultKind == defaultValueKindNone {
 				return "", defaultValueKindNone
 			}
 
-			_, genDefaultKind := typeDefault(genericDef.Fields[i].Type, contextNamespace, "", st)
```
Comment (johnstairs) [inline tooling/internal/python/types/types.go:926]: Don't know what I was trying to do here :)

**Comment by naegelejd** [comment]
> There is another issue.
> 
> ```yaml
> MyRec<T>: !record
>   fields:
>     a: T*
> ```
> 
> Does not default the field, whereas this does:
> 
> ```yaml
> MyRec: !record
>   fields:
>     a: int*
> ```
> 
> (An existing issue, not a regression)

I'm going to open a separate issue for this one you discovered ("generic vector default")

**Review by johnstairs — APPROVED** [review]
